name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

# 允許此 job 複製 Pages 內容與獲取 OIDC token
permissions:
  contents: read
  pages: write
  id-token: write

# 避免多個部署並行衝突
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Download and extract Roland MT-32 ROMs
        run: |
          curl -L -o mt32_roms.zip https://archive.org/download/mame-versioned-roland-mt-32-and-cm-32l-rom-files/MT-32_v1.07_legacy_ROM_files.zip
          unzip mt32_roms.zip -d ./dist
          rm mt32_roms.zip

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # 部署 dist 目錄下的所有靜態資源
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
